"""auto update 2026-08-31 10:49

Revision ID: 465368d9dd59
Revises: df4e7e87eb7e
Create Date: 2026-08-31 10:49:47.692839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '465368d9dd59'
down_revision: Union[str, None] = 'df4e7e87eb7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_stats', 'happy_travelers')
    op.drop_column('site_stats', 'completed_trips')
    op.drop_column('site_stats', 'satisfaction_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_stats', sa.Column('satisfaction_percent', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('site_stats', sa.Column('completed_trips', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('site_stats', sa.Column('happy_travelers', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
