"""auto update 2026-08-30 22:28

Revision ID: bc4d630b9119
Revises: 252424567209
Create Date: 2026-08-30 22:28:59.099599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bc4d630b9119'
down_revision: Union[str, None] = '252424567209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_stats',
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('satisfaction_percent', sa.Integer(), nullable=False),
    sa.Column('completed_trips', sa.Integer(), nullable=False),
    sa.Column('happy_travelers', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_stats_id'), 'site_stats', ['id'], unique=False)
    op.add_column('tours', sa.Column('technical_level', sa.Integer(), nullable=True))
    op.add_column('tours', sa.Column('min_age', sa.Integer(), nullable=True))
    op.add_column('tours', sa.Column('fitness_level', sa.Integer(), nullable=True))
    op.add_column('tours', sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tours', sa.Column('included', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tours', sa.Column('excluded', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tours', sa.Column('faqs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'faqs')
    op.drop_column('tours', 'excluded')
    op.drop_column('tours', 'included')
    op.drop_column('tours', 'highlights')
    op.drop_column('tours', 'fitness_level')
    op.drop_column('tours', 'min_age')
    op.drop_column('tours', 'technical_level')
    op.drop_index(op.f('ix_site_stats_id'), table_name='site_stats')
    op.drop_table('site_stats')
    # ### end Alembic commands ###
