"""auto update 2026-08-31 10:37

Revision ID: df4e7e87eb7e
Revises: ec95689fdc03
Create Date: 2026-08-31 10:38:40.828113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'df4e7e87eb7e'
down_revision: Union[str, None] = 'ec95689fdc03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
