"""auto update 2026-08-31 08:29

Revision ID: ec95689fdc03
Revises: bc4d630b9119
Create Date: 2026-08-31 08:30:20.177275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ec95689fdc03'
down_revision: Union[str, None] = 'bc4d630b9119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_id'), 'contact_messages', ['id'], unique=False)
    op.add_column('tour_itinerary_days', sa.Column('what_to_expect', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tour_itinerary_days', sa.Column('meals_included', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tour_itinerary_days', sa.Column('transportation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tour_itinerary_days', sa.Column('gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tour_itinerary_days', sa.Column('accommodation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tours', sa.Column('map_embed_url', sa.String(length=1000), nullable=True))
    op.add_column('tours', sa.Column('pricing_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'pricing_options')
    op.drop_column('tours', 'map_embed_url')
    op.drop_column('tour_itinerary_days', 'accommodation')
    op.drop_column('tour_itinerary_days', 'gallery')
    op.drop_column('tour_itinerary_days', 'transportation')
    op.drop_column('tour_itinerary_days', 'meals_included')
    op.drop_column('tour_itinerary_days', 'what_to_expect')
    op.drop_index(op.f('ix_contact_messages_id'), table_name='contact_messages')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
